# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # my_switch is predefined in this Hyper-V setup
  config.vm.network "public_network", bridge: "my_switch" # external switch

  config.vm.provider "hyperv"

config.vm.provider "hyperv" do |h|
  h.enable_virtualization_extensions = true
  h.linked_clone = true
  h.cpus = 2
  h.maxmemory = 4096
  h.memory = 2048
  h.vmname = "websec_server"
end

  config.vm.provision "file", source: "./resources/websec", destination: "/home/vagrant/websec"
  config.vm.provision "file", source: "./resources/packages_websec.txt", destination: "/home/vagrant/packages_websec.txt"
  config.vm.provision "file", source: "./resources/cleanup.sh", destination: "/home/vagrant/cleanup.sh"
  config.vm.provision :shell, path: "bootstrap.sh", privileged: true
end
